### ISSUE TITLE
Nearest Neighbor Scaling

### ISSUE THREAD

**Issue by ThioJoe** [carina-studio/PixelViewer#10]
I zoomed into a small image (256x256) and was surprised to see that nearest neighbor scaling is not used, so it becomes very blurry. I think that should definitely be an option for a tool such as this that lets you see the information about individual pixels. Because right now if you zoom in, it's hard to tell which pixel you're actually hovering on.

Overall I really like the program though, it has come in handy.

See example below - With nearest neighbor you can distinctly see each individual pixel.

Original 256x256 Icon:
![Registry1](https://github.com/carina-studio/PixelViewer/assets/12518330/e4f46255-d1a0-441a-bb56-0587b9f42df8)

Zoomed in with pixelviewer:
<img width="402" alt="image" src="https://github.com/carina-studio/PixelViewer/assets/12518330/f64b3a46-d159-4bf2-833a-4c0020f99070">

Zoomed in with photoshop (nearest neighbor):
<img width="431" alt="image" src="https://github.com/carina-studio/PixelViewer/assets/12518330/36bd7281-0270-4e91-a929-83be05f3c817">

**Comment by carina-studio** [comment]
@ThioJoe Thanks for feedback, we will check how to achieve this.

**Comment by kobenein** [comment]
I have the same requirement!

**Comment by hamster620** [comment]
Hi @kobenein and @ThioJoe , rendering with nearest neighbor when scale >= 1.0 has been implemented in PixelViewer 3.0. We will soon release PixelViewer 3.0 preview with this behavior. Thanks.

<img width="1042" alt="截圖 2023-09-28 下午2 32 40" src="https://github.com/carina-studio/PixelViewer/assets/26860570/11c684b3-9156-457c-b569-958212342e39">

**Comment by hamster620** [comment]
Rendering pixels with nearest neighbor has been released with [PixelViewer 3.0 Preview](https://github.com/carina-studio/PixelViewer/releases/tag/3.0.0.1005).
