### ISSUE TITLE
Can you help support the 14-bit MIPI format?

### ISSUE THREAD

**Issue by Air2018** [carina-studio/PixelViewer#15]

**Comment by Air2018** [comment]
[IMG_w[4096]_h[3072]_stride[7168]_scanline[3072].RAWMIPI14.zip](https://github.com/carina-studio/PixelViewer/files/14680978/IMG_w.4096._h.3072._stride.7168._scanline.3072.RAWMIPI14.zip)


> @Air2018 Is there any sample image with 14-bit MIPI so that I can verify the result? Thanks.

I have uploaded a sample image with 14-bit MIPI.
Thanks

**Comment by hamster620** [comment]
@Air2018 ```Bayer pattern (14-bit MIPI)``` format is now supported in ```3.1.0.326-preview```. Please enable ```Accept non-stable application update``` in the application options dialog then you can upgrade to ```3.1.0.326-preview```.
<img width="742" alt="截圖 2024-03-25 晚上8 49 03" src="https://github.com/carina-studio/PixelViewer/assets/26860570/fe4e733e-f856-472a-8f39-581a264f32e5">

**Comment by Air2018** [comment]
Thanks very much
