### ISSUE TITLE
How to show YUV image with correct colors?

### ISSUE THREAD

**Issue by jigoku1206** [carina-studio/PixelViewer#17]
Hi,

My test image:
[Image_YUYV_1920x1200](https://drive.google.com/file/d/1JUSDBN8-t9A9HEn5C_R-H9iSccSx5Sqh/view?usp=drive_link)

I have a YUYV format image and I want to show the image in PixelViewer.
But It showed a image with incorrect color when I selected YUYV whatever I changed setting.
![image](https://github.com/carina-studio/PixelViewer/assets/28101204/9fe5a31d-b1f9-416e-94e2-dbdc846039b4)

I expect the correct image like below:
![image](https://github.com/carina-studio/PixelViewer/assets/28101204/c0b77e5a-14cc-4af1-84af-3a42f354d755)

I currently set L16 to show mono image to check image but I hope I can get color image with PixelViewer.
![image](https://github.com/carina-studio/PixelViewer/assets/28101204/24e86ca7-24bc-4395-941d-b42f0f72c90a)

Thanks!

**Comment by hamster620** [comment]
@jigoku1206 ```YUYV``` format is not currently supported by PixelViewer. We will add support with next preview release.

**Comment by hamster620** [comment]
Seems the image is ```YVYU``` instead of ```YUYV```. Both formats will be support in next preview release.

**Comment by hamster620** [comment]
@jigoku1206 ```YUYV``` and ```YVYU``` are now supported in [3.1.1.428](https://github.com/carina-studio/PixelViewer/releases/tag/3.1.1.428).

**Comment by jigoku1206** [comment]
Thanks for your help!
