### ISSUE TITLE
Can't do black level correction (blc) to bayer raw.

### ISSUE THREAD

**Issue by siyhust** [carina-studio/PixelViewer#6]
for sensor raw (bayer), we should do blc before adjust the color and luma, otherwise the contrast after adjustment will be a problem.

could you please add blc function? Thanks.

**Comment by carina-studio** [comment]
Support black/white level correction:
- https://github.com/carina-studio/PixelViewer/commit/261f6f5660deab9280928307f27fdf9607d67a25
- https://github.com/carina-studio/PixelViewer/commit/1aa9d382ac97050d4e54a7b183bd3b66853b4681
