### ISSUE TITLE
Something wrong when format is RGB565

### ISSUE THREAD

**Issue by colourfate123** [carina-studio/PixelViewer#7]
When the format is RGB565, the picture is green. (0, 0) pixels are (29, 56, 29), and it doesn't seem to be enlarged to 255.

![image](https://user-images.githubusercontent.com/127209398/223595786-3d7164de-e354-4dc0-9426-bdeb57eed137.png)

**Comment by hamster620** [comment]
Fixed by 8acf978a076e301552bad797197e3fa2922e39ea and released with [2.7.4.312](https://github.com/carina-studio/PixelViewer/releases/tag/2.7.4.312).
