### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.

### ISSUE THREAD

**Issue by chenloveheimei** [carina-studio/PixelViewer#9]
Ｕbuntu20.04

./PixelViewer.

Error:
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.

**Comment by hamster620** [comment]
Fix has been released with [PixelViewer 3.0 Preview](https://github.com/carina-studio/PixelViewer/releases/tag/3.0.0.1005).
